name: First Pipeline

on:
  push:
    branches:
      - dev

jobs:
  terraform_job:
    runs-on: windows-latest
    
    steps:
      - name: Checking Out Repository
        uses: actions/checkout@main
      
      - name: Deploy to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name : Initializing Terraform
        run : make init
      
      - name : Creating SSM Parameters
        run : make ssm_params
      
      - name : creating ECR Repository
        run : make ecr_repo
      
      - name : Pushing Image to ECR Repository
        run : make push_img

      - name : Creating Plan of Resources
        run : make plan
      
      - name : Creating Remaining Resources
        run : make  apply

        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-1'