name: First Pipeline
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    -name : hello-world
     run : echo 'hello world'

     env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}